feat: added labels and locked conversations for new issues
swiftwave-org/bot pull request #7
Opened 2023-10-22 16:19 UTC by looneyD-ROHIT

Added feature
- labels - ['`pending-triage`', '`max-assignees-1`'] for newly created issues
- **locking** the conversation to **issue author** and **organization members**

2023-10-23 11:49 UTC, tanmoysrt requested changes

2023-10-23 11:49 UTC, tanmoysrt commented on add_labels_and_lock_new_issues.js
> +        const issue_labels_response = await octokit.rest.issues.listLabelsOnIssue({
The `issue.details` has already the labels field, so we can use that , we need not to call `listLabelsOnIssue` again.

2023-10-23 11:49 UTC, tanmoysrt commented on add_labels_and_lock_new_issues.js
> +            const hasMaxAssigneesLabel = issue_labels_response.data.some(label => label.name === 'max-assignees-1');
Instead of an exact match, check if there is any label with the prefix `max-assignees-' and the count after it is an integer.

2023-10-23 11:49 UTC, tanmoysrt commented on add_labels_and_lock_new_issues.js
> +            }
instead of calling `addLabels` twice, prepare the list of labels first and do a single API call.

2023-10-23 11:49 UTC, tanmoysrt commented on add_labels_and_lock_new_issues.js
> +                lock_reason: 'spam',
Don't provide any lock reason.

2023-10-23 11:49 UTC, tanmoysrt commented on singletons.js
> +        });
As this portion is going to be used at single place, we can just use it without any separate function creation

2023-10-23 11:49 UTC, tanmoysrt commented on add_labels_and_lock_new_issues.js
> +
Add a guard clause to check event and action before performing the below operation.
This function will be run only when the Issue is created.

```js
if(github.context.eventName === "issue" && github.context.payload.action === "opened" && !issue.isPullRequest()){
    // your code goes here ....
}
```

Just for context, we are also checking whether it's a issue by `!issue.isPullRequest()`
Because, in GitHub, all issues and PRs are considered are Issues.

2023-10-23 18:22 UTC, looneyD-ROHIT commented
kindly check the changes I have done as requested

2023-10-24 13:37 UTC, tanmoysrt commented on add_labels_and_lock_new_issues.js
> +        const issue = Issue.getInstance();
```suggestion
        const issue = await Issue.getInstance();
```

2023-10-24 13:38 UTC, tanmoysrt commented on add_labels_and_lock_new_issues.js
> +            const issue_labels = (await issue.details["labels"]) || [];
```suggestion
            const issue_labels = issue.details.labels;
```

2023-10-24 13:46 UTC, tanmoysrt commented
@looneyD-ROHIT check the comments !

2023-10-24 15:01 UTC, looneyD-ROHIT commented
check it once @tanmoysrt

2023-10-24 15:03 UTC, tanmoysrt commented
> check it once @tanmoysrt

okk! merging after testing

2023-10-24 15:06 UTC, looneyD-ROHIT commented
> @looneyD-ROHIT pls build the package and update in the commit

done

2023-10-24 15:30 UTC, tanmoysrt requested changes

2023-10-24 15:30 UTC, tanmoysrt commented on dist/index.js.cache.js
> +module.exports = { verifyTriageTeam, addLabels };
@looneyD-ROHIT 
The function doesn't exist anymore. So remove and build thee package
```suggestion
module.exports = { verifyTriageTeam };
```

2023-10-25 18:00 UTC, tanmoysrt commented on add_labels_and_lock_new_issues.js
> +        if (github.context.eventName === "issue" && github.context.payload.action === "opened" && !issue.isPullRequest()) {
```suggestion
        if (github.context.eventName === "issues" && github.context.payload.action === "opened" && !issue.isPullRequest()) {
```

2023-10-25 18:12 UTC, tanmoysrt commented
The feature is working as expected. Let's merge 
Great work @looneyD-ROHIT :rocket:

2023-10-25 18:12 UTC, merged

2023-10-25 18:14 UTC, tanmoysrt commented
> The feature is working as expected. Let's merge Great work @looneyD-ROHIT 🚀

@looneyD-ROHIT moved to core team.